{% set version = '0.3.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nanotime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nanotime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nanotime/nanotime_{{ version }}.tar.gz
  sha256: a771782653aef62a071682907fd7bd611f7f98fc80beda227d619aae166ccb15

build:
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib("c") }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-rcppcctz >=0.2.9
    - r-rcppdate
    - r-bit64
    - r-zoo
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcppcctz >=0.2.9
    - r-rcppdate
    - r-bit64
    - r-zoo
test:
  commands:
    - $R -e "library('nanotime')"           # [not win]
    - "\"%R%\" -e \"library('nanotime')\""  # [win]

about:
  home: https://github.com/eddelbuettel/nanotime, https://eddelbuettel.github.io/nanotime/,
    https://dirk.eddelbuettel.com/code/nanotime.html
  license: GPL-2.0-or-later
  summary: Full 64-bit resolution date and time functionality with nanosecond granularity is
    provided, with easy transition to and from the standard 'POSIXct' type. Three additional
    classes offer interval, period and duration functionality for nanosecond-resolution
    timestamps.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
    - conda-forge/r
    - jdblischak
