{% set version = "0.3.15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nanotime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nanotime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nanotime/nanotime_{{ version }}.tar.gz
  sha256: 83b320693bfcb4ab686085c966b490b957be309eaeba5d2d96061083f2764986

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib("c") }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp >=1.1.1               # [build_platform != target_platform]
    - r-rcppcctz >=0.2.9           # [build_platform != target_platform]
    - r-rcppdate                   # [build_platform != target_platform]
    - r-bit64 >=4.8.0              # [build_platform != target_platform]
    - r-zoo                        # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.1.1
    - r-rcppcctz >=0.2.9
    - r-rcppdate
    - r-bit64 >=4.8.0
    - r-zoo
  run:
    - r-base
    - r-rcpp >=1.1.1
    - r-rcppcctz >=0.2.9
    - r-rcppdate
    - r-bit64 >=4.8.0
    - r-zoo

test:
  commands:
    - $R -e "library('nanotime')"           # [not win]
    - "\"%R%\" -e \"library('nanotime')\""  # [win]

about:
  home: https://eddelbuettel.github.io/nanotime/, https://dirk.eddelbuettel.com/code/nanotime.html
  dev_url: https://github.com/eddelbuettel/nanotime
  license: GPL-2.0-or-later
  summary: Full 64-bit resolution date and time functionality with nanosecond granularity is provided, with easy transition to and from the standard 'POSIXct' type. Three additional classes offer interval, period and duration functionality for nanosecond-resolution timestamps.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ihnorton
    - shelnutt2
    - jdblischak
